'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
function ansiColor(codes, input) {
    return '\u001b[' + codes[0] + 'm' + input + '\u001b[' + codes[1] + 'm'
}
exports.default = ansiColor
const curryAnsiColor = codes => input => ansiColor(codes, input)
ansiColor.Black = curryAnsiColor([0, 0])
ansiColor.Red = curryAnsiColor([31, 39])
ansiColor.Green = curryAnsiColor([32, 39])
ansiColor.Yellow = curryAnsiColor([33, 39])
ansiColor.Blue = curryAnsiColor([34, 39])
ansiColor.Magenta = curryAnsiColor([35, 39])
ansiColor.Cyan = curryAnsiColor([36, 39])
ansiColor.White = curryAnsiColor([37, 39])
ansiColor.Gray = curryAnsiColor([90, 39])
ansiColor.Grey = curryAnsiColor([90, 39])
ansiColor.BgBlack = curryAnsiColor([40, 49])
ansiColor.BgRed = curryAnsiColor([41, 49])
ansiColor.BgGreen = curryAnsiColor([42, 49])
ansiColor.BgYellow = curryAnsiColor([43, 49])
ansiColor.BgBlue = curryAnsiColor([44, 49])
ansiColor.BgMagenta = curryAnsiColor([45, 49])
ansiColor.BgCyan = curryAnsiColor([46, 49])
ansiColor.BgWhite = curryAnsiColor([47, 49])
ansiColor.BlackBright = curryAnsiColor([90, 39])
ansiColor.RedBright = curryAnsiColor([91, 39])
ansiColor.GreenBright = curryAnsiColor([92, 39])
ansiColor.YellowBright = curryAnsiColor([93, 39])
ansiColor.BlueBright = curryAnsiColor([94, 39])
ansiColor.MagentaBright = curryAnsiColor([95, 39])
ansiColor.CyanBright = curryAnsiColor([96, 39])
ansiColor.WhiteBright = curryAnsiColor([97, 39])
ansiColor.BgBlackBright = curryAnsiColor([100, 49])
ansiColor.BgRedBright = curryAnsiColor([101, 49])
ansiColor.BgGreenBright = curryAnsiColor([102, 49])
ansiColor.BgYellowBright = curryAnsiColor([103, 49])
ansiColor.BgBlueBright = curryAnsiColor([104, 49])
ansiColor.BgMagentaBright = curryAnsiColor([105, 49])
ansiColor.BgCyanBright = curryAnsiColor([106, 49])
ansiColor.BgWhiteBright = curryAnsiColor([107, 49])
